# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '39 10 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: rm -rf ./_posts

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://gitee.com/pwndrer4/posts.git ./_posts
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./_posts
          git diff --quiet && git diff --staged --quiet || git commit -am 'update posts'
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
